import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import api from "../services/api";
import toast from "react-hot-toast";

const DIVISIONS = ["Philosophy","Science","Politics","Gaming","Cinema","Sports"];
const DIV_ICONS  = { Philosophy:"🦉", Science:"⚗️", Politics:"🏛️", Gaming:"🎮", Cinema:"🎬", Sports:"⚡" };
const DIV_COLORS = { Philosophy:"#9b7fd4", Science:"#4caf82", Politics:"#6b9fb8", Gaming:"#e8604c", Cinema:"#c9a84c", Sports:"#f39c12" };

const AITopics = () => {
  const navigate  = useNavigate();
  const [w]       = useState(window.innerWidth);
  const isMobile  = w < 640;
  const [division, setDivision] = useState("Philosophy");
  const [topics, setTopics]     = useState([]);
  const [loading, setLoading]   = useState(false);
  const [selected, setSelected] = useState(null);

  const generateTopics = async () => {
    setLoading(true);
    setTopics([]);
    setSelected(null);
    try {
      const res = await api.get(`/ai/topics?division=${division}&count=6`);
      setTopics(res.data.data || []);
      toast.success("Fresh topics generated!");
    } catch { toast.error("AI unavailable. Try again."); }
    finally { setLoading(false); }
  };

  const divColor = DIV_COLORS[division];

  return (
    <div style={{ background:"#0a0a0a", minHeight:"100vh" }}>
      <nav style={{ position:"fixed", top:0, left:0, right:0, zIndex:100, padding:isMobile?"0.9rem 1.2rem":"0.9rem 2rem", display:"flex", alignItems:"center", justifyContent:"space-between", background:"#0f0f0fF0", backdropFilter:"blur(12px)", borderBottom:"1px solid #1a1a1a" }}>
        <div style={{ fontFamily:"Cinzel Decorative,serif", fontSize:isMobile?"0.85rem":"1rem", color:"#c9a84c", letterSpacing:"0.2em", cursor:"pointer" }} onClick={()=>navigate("/dashboard")}>VOXIUM</div>
        <motion.button whileHover={{scale:1.05}} whileTap={{scale:0.95}} onClick={()=>navigate("/matchmaking")}
          style={{ background:"linear-gradient(135deg,#c9a84c,#a07830)", border:"none", color:"#0a0a0a", padding:"0.4rem 1rem", fontFamily:"Cinzel,serif", fontSize:"0.68rem", letterSpacing:"0.1em", cursor:"pointer", borderRadius:6, fontWeight:700 }}
        >FIND MATCH ⚔️</motion.button>
      </nav>

      <div style={{ maxWidth:800, margin:"0 auto", padding:isMobile?"5rem 1rem 2rem":"5rem 2rem 2rem" }}>
        <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} style={{ textAlign:"center", marginBottom:"2.5rem" }}>
          <div style={{ fontFamily:"JetBrains Mono,monospace", fontSize:"0.62rem", color:"#c9a84c", letterSpacing:"0.4em", marginBottom:"0.8rem" }}>POWERED BY GEMINI AI</div>
          <h1 style={{ fontFamily:"Cinzel,serif", fontSize:isMobile?"1.8rem":"2.5rem", color:"#f5f0e8", fontWeight:700, marginBottom:"0.5rem" }}>AI Topic Generator</h1>
          <p style={{ color:"#4a4540", fontSize:"0.82rem", fontFamily:"Inter,sans-serif" }}>Fresh controversial debate topics generated by AI for every division</p>
        </motion.div>

        <div style={{ marginBottom:"2rem" }}>
          <div style={{ fontFamily:"Cinzel,serif", fontSize:"0.68rem", color:"#8a8070", letterSpacing:"0.15em", marginBottom:"0.8rem" }}>SELECT DIVISION</div>
          <div style={{ display:"grid", gridTemplateColumns:isMobile?"repeat(3,1fr)":"repeat(6,1fr)", gap:"0.6rem" }}>
            {DIVISIONS.map(d=>(
              <motion.button key={d} whileHover={{scale:1.05}} whileTap={{scale:0.95}}
                onClick={()=>{ setDivision(d); setTopics([]); setSelected(null); }}
                style={{ padding:"0.8rem 0.5rem", borderRadius:10, cursor:"pointer", textAlign:"center", background:division===d?`${DIV_COLORS[d]}15`:"#0d0d0d", border:division===d?`1px solid ${DIV_COLORS[d]}50`:"1px solid #1e1e1e", transition:"all 0.2s" }}
              >
                <div style={{ fontSize:"1.5rem", marginBottom:"0.3rem" }}>{DIV_ICONS[d]}</div>
                <div style={{ fontFamily:"Cinzel,serif", fontSize:"0.6rem", color:division===d?DIV_COLORS[d]:"#8a8070", letterSpacing:"0.08em" }}>{d}</div>
              </motion.button>
            ))}
          </div>
        </div>

        <motion.button whileHover={{scale:1.02,boxShadow:"0 0 30px #c9a84c25"}} whileTap={{scale:0.98}}
          onClick={generateTopics} disabled={loading}
          style={{ width:"100%", padding:"1rem", background:loading?"#5a4a20":"linear-gradient(135deg,#c9a84c,#a07830)", border:"none", borderRadius:10, color:"#0a0a0a", fontFamily:"Cinzel,serif", fontSize:"0.88rem", letterSpacing:"0.15em", cursor:loading?"not-allowed":"pointer", fontWeight:700, marginBottom:"1.5rem" }}
        >{loading?"🤖 Generating topics...":"GENERATE AI TOPICS 🤖"}</motion.button>

        <AnimatePresence>
          {topics.length>0 && (
            <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}>
              <div style={{ fontFamily:"Cinzel,serif", fontSize:"0.68rem", color:"#4a4540", letterSpacing:"0.1em", marginBottom:"0.8rem" }}>CLICK A TOPIC TO SELECT IT</div>
              <div style={{ display:"flex", flexDirection:"column", gap:"0.6rem", marginBottom:"1.5rem" }}>
                {topics.map((topic,i)=>(
                  <motion.div key={i}
                    initial={{opacity:0,x:-20}} animate={{opacity:1,x:0}} transition={{delay:i*0.08}}
                    onClick={()=>setSelected(i)}
                    whileHover={{x:4,borderColor:`${divColor}40`}}
                    style={{ padding:"1rem 1.2rem", background:selected===i?"#1a1408":"#111", border:selected===i?`1px solid ${divColor}`:"1px solid #1e1e1e", borderRadius:10, cursor:"pointer", display:"flex", alignItems:"center", gap:"1rem", transition:"all 0.2s" }}
                  >
                    <div style={{ width:24, height:24, borderRadius:"50%", background:selected===i?divColor:"#1a1a1a", display:"flex", alignItems:"center", justifyContent:"center", fontSize:"0.65rem", color:selected===i?"#0a0a0a":divColor, fontFamily:"Cinzel,serif", fontWeight:700, flexShrink:0 }}>{i+1}</div>
                    <div style={{ fontFamily:"Inter,sans-serif", fontSize:isMobile?"0.82rem":"0.88rem", color:selected===i?"#f5f0e8":"#8a8070", lineHeight:1.5, flex:1 }}>{topic}</div>
                    {selected===i && <div style={{ color:divColor, fontSize:"0.8rem", flexShrink:0 }}>✓</div>}
                  </motion.div>
                ))}
              </div>
              {selected!==null && (
                <motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}>
                  <div style={{ background:"#1a1408", border:`1px solid ${divColor}30`, borderRadius:10, padding:"1rem", marginBottom:"1rem", textAlign:"center" }}>
                    <div style={{ fontFamily:"JetBrains Mono,monospace", fontSize:"0.6rem", color:divColor, letterSpacing:"0.2em", marginBottom:"0.4rem" }}>SELECTED TOPIC</div>
                    <div style={{ fontFamily:"Inter,sans-serif", fontSize:"0.88rem", color:"#f5f0e8" }}>"{topics[selected]}"</div>
                  </div>
                  <motion.button whileHover={{scale:1.03,boxShadow:"0 0 30px #c9a84c30"}} whileTap={{scale:0.97}}
                    onClick={()=>navigate("/matchmaking")}
                    style={{ width:"100%", padding:"0.9rem", background:"linear-gradient(135deg,#c9a84c,#a07830)", border:"none", borderRadius:8, color:"#0a0a0a", fontFamily:"Cinzel,serif", fontSize:"0.85rem", letterSpacing:"0.12em", cursor:"pointer", fontWeight:700 }}
                  >DEBATE THIS TOPIC ⚔️</motion.button>
                </motion.div>
              )}
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
};

export default AITopics;